### PR TITLE
Fix #79

### LINKED ISSUE #79: Massive memory consumption when generating newick trees
together with large sample sizes, e.g.

```
scrm 3359 100 -r 19999.9996 50000000 -T  -l 0
```

takes multiple gigabytes. This should be related to the caching of newick subtrees.

Possible solutions:

* cache only a fraction of nodes
* remove nodes as soon as they become non-local
* add option to disable the caching or disable it automatically for large sample sizes (least preferred)

### PR DESCRIPTION
**Pull request by paulstaab**
fixes #79

### CODE REVIEW

**Comment by paulstaab** [comment]
Command | Equal results | time master | time fix/issue_79 | memory master | memory fix/issue_79
------- | ------------- | ----------- | -------- | ------------- | ---------
scrm 100 100 -t 5 -T | Yes | 0.1s | 0.091s | 3185kb | 3137kb
scrm 20 100 -r 10 100 -t 3 -T -L | Yes | 0.078s | 0.09s | 3164kb | 3122kb
scrm 4 10000 -r 10 100 -t 5 | Yes | 0.53s | 0.53s | 3044kb | 3033kb
scrm 20 2 -r 500 100 -L | Yes | 0.15s | 0.15s | 3190kb | 3190kb
scrm 2000 1 -r 10 100 -l 50 -L -T | Yes | 0.57s | 0.55s | 9438kb | 5974kb
scrm 20 1 -r 4000 10000000 -l 300000 -T | Yes | 0.85s | 0.9s | 11928kb | 4388kb
scrm 500 1 -r 1000 10000000 -l 0 -T | Yes | 1.1s | 0.69s | 112935kb | 3880kb
scrm 100 1 -r 400 10000000 -l 0 -O | Yes | 0.28s | 0.29s | 10901kb | 3165kb
scrm 10 100 -r 10 100 -I 3 3 3 4 0.5 -eN 0.1 0.05 -eN 0.2 0.5 -L | Yes | 0.054s | 0.054s | 3106kb | 3112kb
scrm 50 100 -r 20 200 -G 1.5 -l 100 -L | Yes | 0.047s | 0.046s | 3135kb | 3126kb

**Comment by gerton** [comment]
Well done — great fix!

BW
G

**Comment by shajoezhu** [comment]
:+1:

**Comment by paulstaab** [comment]
Thanks. I guess there is still some room for optimization when generating the trees, but I'm a but short on time right now...

**Pull request merged**
